### ISSUE TITLE
Support 1.12.2

### ISSUE THREAD

**Issue by elifoster** [elifoster/Ping#14]
self explanatory

**Comment by xbony2** [comment]
bump

**Comment by Triple7Factor** [comment]
ping :)

**Comment by elifoster** [comment]
@xbony2 @Triple7Factor Yeah, I'd like to get this resolved asap. I've been having issues with my dev environment for this mod specifically, for some reason. Hopefully I'll figure that out soon.

#15 (just tagging this here so the issue and PR you submitted, Triple7Factor, are linked to one another).
