### ISSUE TITLE
invisible chat(commands) with other mods

### ISSUE THREAD

**Issue by SingingPandi** [elifoster/Ping#6]
When I use this mod, the commands like /help or so are invisible, if I use mods like MoreCommands or something like that.
I really would appreciate it, if you could look into this matter.

"you casted the generic TextComponent type of a chat message to a TextComponentTranslation for all messages without checking if they actually are of this type. (There should be a "ClassCastException" in the log files and in the launcher log)"

**Comment by elifoster** [comment]
What Minecraft versions does this occur on?

**Comment by elifoster** [comment]
Never mind, it will happen with all versions. I'll fix it for 1.7, 1.8, and 1.9 right now.

**Comment by elifoster** [comment]
Closed by 9aefb59, bbd5ad8, and d0553e3 and they are all available on CurseForge. Thanks for reporting 😸
